image: node:latest

stages:
  - pages

pages:
  stage: pages
  script:
    - cp ./CNAME public/ && cp ./index.html public/ && cp ./favicon.ico public/
  artifacts:
    paths:
      - public
  only:
    - master
